### ISSUE TITLE
SOFA 飞船——Layotto 星球登陆计划

### ISSUE THREAD

**Issue by Kelei0215** [mosn/layotto#776]
## 一、背景

SOFAStack 是一个基于金融级分布式架构技术探索的开源社区。这次 SOFAStack 启动 SOFA 飞船，踏上充满挑战的星球登陆之旅，旅途第一站来到了 Layotto 星球。星球登陆任务已被打包放在星球上的各个空间站，想要成为开源先锋的小伙伴快来参与探索，做进击的开源人吧！

Layotto 是一款使用 Golang 开发的应用运行时, 旨在帮助开发人员快速构建云原生应用，帮助应用和基础设施解耦。Layotto 提供了各种分布式的能力，比如状态管理、配置管理、事件发布订阅等能力，以简化应用的开发。 

> *前期在“飞船计划”活动未完成的任务，合并后积分会更新进排行榜*

## 二、探索空间站

我们会持续发掘更新 Layotto 星球上的各个空间站。小伙伴们可以加入自己感兴趣的空间站并进行探索，通过任务实现积累能量值，去成为空间站站长，带领更多本站的小伙伴完成星球登陆吧！

#### 已探寻到的空间站一览

● **Component 空间站**：***New！***

- [ ] [为“延迟消息 API”开发新的组件 #840 *New*](https://github.com/mosn/layotto/issues/840)
- [ ] [为 email API 开发新的组件 #836 *New*](https://github.com/mosn/layotto/issues/836)
- [ ] [为“短信 API”开发新的组件 #830 *New*](https://github.com/mosn/layotto/issues/830)
- [ ] [集成 wasmtime 运行时 #755](https://github.com/mosn/layotto/issues/755)
   包含：minIO、ceph、tencent cloud、qiniu cloud、azure、gcp
- [ ] [让阿里云 OSS 组件不用配密钥 #748](https://github.com/mosn/layotto/issues/748)

● **Documentation 空间站**：

- [x] [把代码生成器的使用文档翻译成中文 #797](https://github.com/mosn/layotto/issues/797) 已合并

● **Bug 空间站**：

- [x] [he sayHello demo fails #757](https://github.com/mosn/layotto/issues/757) 已合并

● **Demo 空间站**：

- [ ] [在 quickstart 中添加 Javscript demo #686](https://github.com/mosn/layotto/issues/686)
- [x] [在 configuration API quickstart 中添加 java demo #687](https://github.com/mosn/layotto/issues/687) 已合并
- [x] [在 lock API quickstart 中添加 java demo #688](https://github.com/mosn/layotto/issues/688) 已合并
- [ ] [在 secret API quickstart 中添加 java demo #689](https://github.com/mosn/layotto/issues/689)
- [ ] [在 RPC quickstart 中添加 java demo #690](https://github.com/mosn/layotto/issues/690)

● **WebAssembly 空间站**：

- [ ] [设计 FaaS 编程 API #611](https://github.com/mosn/layotto/issues/611)
- [ ] [为 wasm 模块补充单测 #105](https://github.com/mosn/layotto/issues/105)

#### 能量获取：

1.完成一个 Easy 的空间站任务可收集 2 颗能量值。

2.完成一个 Medium 的空间站任务可收集 4 颗能量值。

3.完成一个 Hard 的空间站任务可收集 10 颗能量值。

4.在单个空间站获取能量值数量 >=10（*当中至少完成 1 个 Medium 任务*）的小伙伴，可以成为该空间站的站长（*Reviewer*），查看更多人的任务 PR，帮助更多小伙伴登陆 Layotto 星球！

> *更多关于社区晋升与成长的说明，可以查看 [Layotto 社区晋升规则](https://mosn.io/layotto/#/zh/community/promote) 了解更多哦～*

## 三、星球登陆指引

1.参与者登陆自己的 GitHub 账号进入活动 issue 页，挑选出自己想要加入的空间站，在感兴趣的星球登陆任务下评论“/assign”领取任务开始探索；

2.在规定时间内完成领取的任务后提交 PR，“ Layotto 星球领航员”（*Committer*）或所在的空间站的站长（*Reviewer*）会进行 review；

3.提交的 PR 审核通过后，即达成任务，获得相应的能量值；

4.重复以上流程，继续探索空间站，成为“Layotto 空间站站长”（*Reviewer*）；

5.帮助 review 其他小伙伴的任务 PR，带领空间站成员继续探索挑战。

#### 注意事项

1.每位参与者 1 次至多可认领 1 个任务，1 人可认领完成多次。

2.本次任务难度分为 3 个等级：Easy，Medium，Hard。

3.任务根据不同难度设置了对应的提交期限：Easy 任务认领后请于 10 天内提交，Medium 任务认领后请于 15 天内提交，Hard 任务认领后请于 20 天内提交。

> *如过期未提交将被视作放弃该任务，任务将会被重新释放。我们每周会通过“金融级分布式架构”公众号同步活动的进展情况。*

## 四、空间站福利

活动到期结束时，我们将公布最终的星球登陆计划进展，为在本期活动中新晋的“空间站站长”（*Reviewer*）和“星球领航员”（*Committer*）发放终极奖励，包括社区 Reviewer/Committer 证书，文章专栏宣传和社区周边礼物等；

另外，我们将统一发放社区周边小礼品以鼓励参与“Layotto 星球登陆计划”的其他小伙伴（贴纸/钥匙链等）💕

> ***有任何问题欢迎微信添加 SOFAGirl180419 备注飞船任务，或加入钉钉群 41585216（Layotto 社区）***
